/**
 * Example of moment usage.
 *
 * @export
 * @class ExampleMoment
 */
import {customElement, property} from "@polymer/decorators/src/decorators";
import {Element as PolymerElement} from "@polymer/polymer/polymer-element";
import /* Synthetic Import */ moment from "moment";
import /* Synthetic Import */ template from "./example-moment.html";

@customElement("co-example-moment")
export class ExampleMoment extends PolymerElement {
    /**
     * Current date and time displayed in the view.
     * @type {string}
     */
    @property({type: String})
    public currentDateTime: string;

    /**
     * Creates an instance of ExampleMoment.
     */
    constructor() {
        super();
        window.setInterval(() => {
            this.currentDateTime = moment().format("YYYY-MM-DD HH:mm:ss");
        },
        1000);
    }

    /**
     * Get the template.
     * @readonly
     * @static
     * @returns {string}
     */
    static get template(): string {
        return `${template}`;
    }
}

// Generated by UniteJS
