/**
 * Tests for Rxjs Example.
 */
/// <reference types="unitejs-protractor-plugin"/>
import { $, browser, by, element, protractor } from "protractor";
import { loadExampleElement } from "../helpers/element-helper";

describe("ExampleRxjs", () => {
    it("the example result is correct", (done) => {
        loadExampleElement("Rxjs")
            .then((elem) => {
                const btn = elem.element(by.css("button"));
                btn.click();
                btn.click();
                btn.click();
                elem.element(by.css("span")).getText()
                    .then((result) => {
                        expect(result).toEqual("Clicked 3 times!");
                        done();
                    });
            });
    });
});

// Generated by UniteJS
